const $ = s => document.querySelector(s); const app=$('#app'), nav=$('#nav');
const questions=[
 ['3 Idiots','👨‍🎓 🤪 🧪 🏫',['3 idiots','three idiots'],'Easy','Bollywood'],['Dangal','🤼 👨‍👧‍👧 🥇',['dangal'],'Easy','Bollywood'],['Sholay','🔥 🏍️ 👬 🦹',['sholay'],'Easy','Bollywood'],['Kabhi Khushi Kabhie Gham','👨‍👩‍👧‍👦 😢 🏠 ❤️',['kabhi khushi kabhie gham','kabhi khushi kabhie gham'],'Medium','Bollywood'],['Dilwale Dulhania Le Jayenge','🚂 ❤️ 🇮🇳',['dilwale dulhania le jayenge','ddlj'],'Easy','Bollywood'],['Zindagi Na Milegi Dobara','👬 🚗 🌊 🇪🇸',['zindagi na milegi dobara','znmd'],'Medium','Bollywood'],['Chennai Express','🚂 ❤️ 🌴',['chennai express'],'Easy','Bollywood'],['Lagaan','🏏 🌾 🇮🇳',['lagaan'],'Easy','Bollywood'],['Taare Zameen Par','⭐ 🌍 👦 🎨',['taare zameen par'],'Easy','Bollywood'],['Queen','👑 ✈️ 🗼',['queen'],'Easy','Bollywood'],['PK','👽 📻 ❓',['pk','p k'],'Easy','Bollywood'],['Om Shanti Om','🎬 🔥 ❤️ 🔄',['om shanti om'],'Medium','Bollywood'],['Don','🕶️ 🔫 🕵️',['don'],'Easy','Bollywood'],['Bhool Bhulaiyaa','👻 🏰 💃',['bhool bhulaiyaa','bhool bhulayya'],'Easy','Bollywood'],['Koi Mil Gaya','👦 👽 🚲',['koi mil gaya','koi milgaya'],'Easy','Bollywood'],['Kal Ho Naa Ho','❤️ ⏳ 🗽',['kal ho naa ho','kal ho na ho'],'Medium','Bollywood'],['Munna Bhai M.B.B.S.','🩺 😄 🏥',['munna bhai mbbs','munna bhai m.b.b.s','munna bhai m.b.b.s.'],'Medium','Bollywood'],['Hera Pheri','☎️ 💰 😂',['hera pheri'],'Easy','Bollywood'],['Jab We Met','🚂 👩 ❤️',['jab we met'],'Easy','Bollywood'],['Gully Boy','🎤 🛣️ ⭐',['gully boy'],'Easy','Bollywood'],['Singham','🦁 👮 🚓',['singham'],'Easy','Bollywood'],['Drishyam','👨‍👩‍👧 📺 🕵️',['drishyam'],'Medium','Bollywood'],['Titanic','🚢 🧊 ❤️',['titanic'],'Easy','Hollywood'],['The Lion King','🦁 👑 🌅',['the lion king','lion king'],'Easy','Hollywood'],['Harry Potter','⚡ 🧙 🏰',['harry potter'],'Easy','Hollywood'],['Home Alone','🏠 👦 🎄',['home alone'],'Easy','Hollywood'],['Jurassic Park','🦖 🏞️',['jurassic park'],'Easy','Hollywood'],['The Avengers','🦸 ⚡ 🌍',['the avengers','avengers'],'Easy','Hollywood'],['Spider-Man','🕷️ 🧑 🏙️',['spider man','spiderman'],'Easy','Hollywood'],['Frozen','❄️ 👸 ⛄',['frozen'],'Easy','Hollywood'],['Avatar','🔵 🌳 🌌',['avatar'],'Easy','Hollywood'],['The Dark Knight','🦇 🌃 🃏',['the dark knight','dark knight'],'Medium','Hollywood'],['Finding Nemo','🐠 🔎 🌊',['finding nemo'],'Easy','Hollywood'],['Toy Story','🤠 🧸 🚀',['toy story'],'Easy','Hollywood']
].map(([title,emoji,answers,difficulty,category])=>({title,emoji,answers,difficulty,category,points:100}));
const messages=['Thank you for believing in us.','Your lessons stay with us long after the bell rings.','Thank you for making school more than just classrooms and textbooks.','You saw potential in us before we could see it ourselves.','Because of you, we keep asking better questions.','The kindness you bring to every class matters more than you know.'];
let player=JSON.parse(sessionStorage.getItem('td-player')||'null'), game=null, currentRoute='welcome';
function escape(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}function norm(s){return String(s).toLowerCase().replace(/[^a-z0-9]/g,'');}
function burst(n=48){const box=$('#confetti');for(let i=0;i<n;i++){const c=document.createElement('i');c.className='conf';c.style.left=Math.random()*100+'%';c.style.setProperty('--drift',(Math.random()*220-110)+'px');c.style.background=['#f7c769','#fa8daf','#73ead0','#dce4ff'][i%4];c.style.animationDelay=Math.random()*.5+'s';box.append(c);setTimeout(()=>c.remove(),4500)}}
function shell(html, route){app.innerHTML=html; currentRoute=route;nav.classList.toggle('hidden',!player||['welcome','name'].includes(route));nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.go===route));window.scrollTo(0,0)}
function welcome(){shell(`<section class="hero"><div class="eyebrow">Teachers' Day • 2026</div><h1>Today, the classroom belongs to <em>you.</em></h1><div class="promise"><p>You teach.</p><p>You inspire.</p><p>You challenge us.</p><p>You make us better.</p></div><p class="closing">Today, we celebrate YOU.<span>Happy Teachers’ Day! ♥</span></p><button class="btn" id="enter">ENTER THE CELEBRATION →</button></section>`,'welcome');$('#enter').onclick=nameEntry;}
function nameEntry(){shell(`<section class="welcome-card"><div class="eyebrow">Before we begin</div><h1>What should we call you?</h1><p>Just a name — so we can cheer you on properly.</p><form id="nameForm"><input class="text-input" autofocus maxlength="50" required placeholder="Enter your name"/><button class="btn" style="width:100%">LET’S PLAY 🎮</button></form></section>`,'name');$('#nameForm').onsubmit=e=>{e.preventDefault();player={name:e.target.querySelector('input').value.trim(),sessionId:crypto.randomUUID(),submitted:false};sessionStorage.setItem('td-player',JSON.stringify(player));home();};}
function home(){shell(`<div class="top"><div><div class="eyebrow">Teachers’ Day Arcade</div><h1 class="home-title">Welcome, <b>${escape(player.name)}</b> 👋</h1><p class="sub">Think fast. Guess smart. Climb the leaderboard.</p></div></div><section class="game-card"><div class="game-icon">🎬</div><div class="eyebrow">Featured game</div><h2>Emoji Movie Mayhem</h2><p>Ten movies. Fifteen seconds each. A little friendly glory.</p><button class="btn" id="startGame">START PLAYING →</button></section><div class="section-label">Explore the celebration</div><div class="quick"><button data-go="leaderboard"><span>♛</span>Leaderboard</button><button data-go="wall"><span>♡</span>Teacher Wall</button><button id="surprise"><span>✦</span>Celebration</button></div></div>`,'home');$('#startGame').onclick=startGame;$('#surprise').onclick=()=>burst();}
function startGame(){let shuffled=[...questions].sort(()=>Math.random()-.5);game={items:shuffled.slice(0,10),index:0,score:0,correct:0,answered:false};showQuestion();}
function showQuestion(){const q=game.items[game.index];game.answered=false;let left=15;const draw=()=>{const p=Math.max(0,left/15*100);shell(`<div class="top"><div><div class="round">Round ${game.index+1} / 10</div><h1>Movie Mayhem</h1></div><div class="timer" style="--pct:${p}%"><b>${left}</b></div></div><div class="progress"><i style="width:${game.index/10*100}%"></i></div><section class="card game-card"><div class="emoji-clue">${q.emoji}</div><p class="guess">Guess the movie</p><form class="answer-form" id="answerForm"><input class="text-input" autocomplete="off" autofocus placeholder="Type your answer"/><button class="btn">SUBMIT ANSWER</button></form></section>`,'arcade');$('#answerForm').onsubmit=e=>{e.preventDefault();answer(e.target.querySelector('input').value,left);};};draw();const timer=setInterval(()=>{if(game.answered){clearInterval(timer);return;}left--;if(left<=0){clearInterval(timer);answer('',0);}else {const t=$('.timer');if(t){t.style.setProperty('--pct',left/15*100);t.querySelector('b').textContent=left;}}},1000);}
function answer(value,left){if(game.answered)return;game.answered=true;const q=game.items[game.index],correct=q.answers.some(a=>norm(a)===norm(value));const points=correct?100+Math.round(left/15*50):0;if(correct){game.correct++;game.score+=points;burst(20)}shell(`<div class="feedback card"><div class="eyebrow">${correct?'Beautifully done':'The answer was'}</div><h2>${correct?'CORRECT! 🎉':'NOT QUITE! 😭'}</h2><p>${correct?`+${points} points`:'No points this round'}<br/>The movie was <strong>${q.title}</strong>.</p><button class="btn" id="next">${game.index===9?'SEE MY RESULTS →':'NEXT ROUND →'}</button></div>`,'arcade');$('#next').onclick=()=>{game.index++;game.index===10?results():showQuestion();};}
async function results(){burst();let rank='—';if(!player.submitted){try{const r=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...player,score:game.score,correct:game.correct})});const d=await r.json();if(r.ok){rank='#'+d.rank;player.submitted=true;player.lastEntryId=d.entry.id;sessionStorage.setItem('td-player',JSON.stringify(player));}}catch{rank='offline';}}shell(`<section class="score-hero"><div class="eyebrow">🎉 Game complete!</div><h1>Great job, ${escape(player.name)}!</h1><div class="score-number">${game.score}</div><div class="sub">YOUR SCORE</div><div class="score-grid" style="margin-top:24px"><div class="stat"><b>${game.correct} / 10</b><span>Correct answers</span></div><div class="stat"><b>${rank}</b><span>Current position</span></div></div></section><div class="row"><button class="btn" id="board">VIEW LEADERBOARD</button><button class="btn secondary" id="again">PLAY AGAIN</button></div>`,'results');$('#board').onclick=leaderboard;$('#again').onclick=()=>{player.sessionId=crypto.randomUUID();player.submitted=false;sessionStorage.setItem('td-player',JSON.stringify(player));startGame();};}
async function leaderboard(){shell(`<div class="top"><div><div class="eyebrow">Live scores</div><h1>🏆 Leaderboard</h1><p class="sub">Teachers’ Day Arcade</p></div><button class="btn secondary" id="refresh">↻</button></div><section class="card game-card"><div class="leaderboard" id="rows"><p class="sub center">Loading the latest scores…</p></div></section>`,'leaderboard');async function load(){try{const data=await (await fetch('/api/leaderboard')).json();$('#rows').innerHTML=data.entries.length?data.entries.map((x,i)=>`<div class="leader-row ${x.id===player.lastEntryId?'me':''}"><div class="rank">${['🥇','🥈','🥉'][i]||i+1}</div><div><div class="leader-name">${escape(x.name)}</div><div class="leader-date">${x.correct}/10 correct</div></div><div class="leader-score">${x.score}</div></div>`).join(''):`<p class="sub center">Be the first to make the board.</p>`;}catch{$('#rows').innerHTML='<p class="sub center">Unable to load the board right now.</p>';}}$('#refresh').onclick=load;load();}
function wall(){const picks=[...messages].sort(()=>Math.random()-.5).slice(0,3);shell(`<div class="top"><div><div class="eyebrow">From your students</div><h1>💌 A message for you</h1><p class="sub">A few words, meant wholeheartedly.</p></div></div>${picks.map((m,i)=>`<article class="wall-card card"><small>WITH GRATITUDE · ${String(i+1).padStart(2,'0')}</small><p>“${m}”</p><small>— YOUR STUDENTS</small></article>`).join('')}<button class="btn pink" id="final">A FINAL CELEBRATION →</button>`,'wall');$('#final').onclick=finale;}
function finale(){burst(80);shell(`<section class="final"><article class="card"><div class="eyebrow">Teachers' Day</div><h1><b>${escape(player.name)},</b><br/>this day is for you.</h1><p>Thank you for teaching us, inspiring us, and being part of our journey.</p><p style="color:var(--pink);font-weight:800">Happy Teachers’ Day! ♥</p><button class="btn" id="back">BACK TO THE ARCADE</button></article></section>`,'final');$('#back').onclick=home;}
nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;({home,arcade:()=>game?showQuestion():startGame,leaderboard,wall}[b.dataset.go]||home)();});
player?home():welcome();
